var about = new Vue({
    el:"#guestbook",
    data:{
        guestbook_list:[
            {
                name:'院长瓜',
                ctime:'12322',
                content:'你的留言板时真的很炫酷'
            },
            {
                name:'院长瓜',
                ctime:'12322',
                content:'你的留言板时真的很炫酷'
            },
            {
                name:'院长瓜',
                ctime:'12322',
                content:'你的留言板时真的很炫酷'
            },
            {
                name:'院长瓜',
                ctime:'12322',
                content:'你的留言板时真的很炫酷'
            },
            {
                name:'院长瓜',
                ctime:'12322',
                content:'你的留言板时真的很炫酷'
            },
            {
                name:'院长瓜',
                ctime:'12322',
                content:'你的留言板时真的很炫酷'
            },
            {
                name:'院长瓜',
                ctime:'12322',
                content:'你的留言板时真的很炫酷'
            }
        ]
    }
})